language: ruby
cache: bundler
addons:
  sauce_connect: true

rvm:
- 2.1

install:
- bundle install
- npm install
- npm run compile

- node --version
- npm --version
- tsc --version

before_script:
- 'export DISPLAY=:99.0'
- 'sh -e /etc/init.d/xvfb start'  # From https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

script:
- set -e # Exit on any error
# Confirm that there is one test for every tsc
- diff <(for FILE in `ls tests/tests`; do basename $FILE; done | perl -pne 's/_test.js//;s/.todo//' | sort) <(for FILE in `ls src/*.ts`; do basename $FILE; done | perl -pne 's/.ts//' | sort)
- PORT=5000
- bundle exec ruby -run -e httpd . -p $PORT &
- QUERY=`cd tests/tests; ls *.js | perl -pne 's/.js//;s/^/test=/' | xargs | tr ' ' '&'`
- TEST_URL=http://localhost:$PORT/tests/qunit.html?$QUERY
- until ( curl -I $TEST_URL | grep '200 OK' ); do sleep 1; done
- bundle exec ruby tests/test.rb $TEST_URL

sudo: false # container-based infrastructure for a faster build