language: ruby
cache: bundler
addons:
  firefox: "47.0.1"

rvm:
- 2.1

install:
- bundle install
- 'npm install -g typescript@1.8.0'
- 'npm install -g typings'
- typings install
# TODO: Compile all the things
- tsc main.ts iterator.ts range.ts matrix.ts matrix_impl.ts vis.ts datatype.ts --target ES5 --module amd

before_script:
- 'export DISPLAY=:99.0'
- 'sh -e /etc/init.d/xvfb start'  # From https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

script:
- set -e # Exit on any error
- PORT=5000
- bundle exec ruby -run -e httpd . -p $PORT &
- QUERY=`ls tests/*.js | perl -pne 's/.js//;s/^/test=/' | xargs | tr ' ' '&'`
- TEST_URL=http://localhost:$PORT/tests/qunit.html?$QUERY
- until ( curl -I $TEST_URL | grep '200 OK' ); do sleep 1; done
- bundle exec ruby tests/test.rb $TEST_URL

sudo: false # container-based infrastructure for a faster build